# Generated by Django 5.2.15 on 2026-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ref', models.CharField(max_length=20, unique=True)),
                ('tutor_name', models.CharField(max_length=200)),
                ('session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('session_date', models.CharField(blank=True, max_length=50, null=True)),
                ('session_subject', models.CharField(blank=True, max_length=300, null=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('checklist_item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('checklist_item_name', models.CharField(blank=True, max_length=300, null=True)),
                ('issue_type', models.CharField(choices=[('not_met', 'Not Met'), ('partially_met', 'Partially Met'), ('manual', 'Manual')], max_length=20)),
                ('risk', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber')], max_length=20)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('system', 'System'), ('manual', 'Manual')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tutor_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
