# Generated by Django 5.2.15 on 2026-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
