# Generated by Django 5.2.15 on 2026-06-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_evidence/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tutor_ticket_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
