# Generated by Django 5.0.1 on 2026-02-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.doctorprofile'),
        ),
        migrations.AddField(
            model_name='group',
            name='modules',
            field=models.ManyToManyField(related_name='groups', to='academics.module'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.group'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['doctor', 'start_date'], name='groups_doctor__c83ffd_idx'),
        ),
    ]
