# Generated by Django 5.0.1 on 2026-02-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('session_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('met_count', models.IntegerField(default=0)),
                ('partial_count', models.IntegerField(default=0)),
                ('not_met_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.doctorprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.module')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-session_date'],
                'indexes': [models.Index(fields=['doctor', 'session_date'], name='sessions_doctor__d7655f_idx'), models.Index(fields=['group', 'session_date'], name='sessions_group_i_f18873_idx')],
            },
        ),
    ]
