# Generated by Django 5.0.1 on 2026-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KbcUserData',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, db_column='FullName', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
                ('minimum', models.DecimalField(blank=True, db_column='Minimum', decimal_places=2, max_digits=12, null=True)),
                ('planned', models.DecimalField(blank=True, db_column='Planned', decimal_places=2, max_digits=12, null=True)),
                ('submitted', models.DecimalField(blank=True, db_column='Submitted', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'kbc_users_data',
                'managed': False,
            },
        ),
    ]
